name: Publish NPM package

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/npm-publish.yml
      - src/ClientSDK/Node/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          always-auth: true
          cache: "yarn"
          cache-dependency-path: src/ClientSDK/Node/yarn.lock

      - name: Yarn install, build
        working-directory: src/ClientSDK/Node
        run: |
          yarn install
          yarn build

      - name: Yarn publish
        working-directory: src/ClientSDK/Node
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          yarn publish --patch
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
